import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

/// Central SF Symbol → Flutter icon mapping so ported views can keep the
/// original symbol names from the SwiftUI source.
class SBIcons {
  SBIcons._();

  static const Map<String, IconData> _map = {
    'alarm': Icons.alarm,
    'alarm.fill': Icons.alarm_on,
    'applelogo': Icons.apple,
    'arrow.clockwise': Icons.refresh,
    'arrow.counterclockwise': Icons.undo,
    'arrow.counterclockwise.circle': Icons.replay_circle_filled_outlined,
    'arrow.left.arrow.right': Icons.swap_horiz,
    'arrow.right': Icons.arrow_forward,
    'arrow.right.circle.fill': Icons.arrow_circle_right,
    'arrow.triangle.2.circlepath': Icons.sync,
    'arrow.triangle.branch': Icons.account_tree_outlined,
    'arrow.up.arrow.down': Icons.swap_vert,
    'arrow.up.doc': Icons.upload_file,
    'arrow.up.left': Icons.north_west,
    'arrow.up.right': Icons.north_east,
    'arrow.up.right.square': Icons.open_in_new,
    'atom': Icons.blur_circular,
    'bag': Icons.shopping_bag_outlined,
    'bandage': Icons.healing_outlined,
    'banknote': Icons.payments_outlined,
    'bell': Icons.notifications_none,
    'bell.badge': Icons.notifications_active_outlined,
    'bolt': Icons.bolt_outlined,
    'bolt.fill': Icons.bolt,
    'book': Icons.menu_book_outlined,
    'book.closed': Icons.book_outlined,
    'books.vertical': Icons.library_books_outlined,
    'books.vertical.fill': Icons.library_books,
    'brain.head.profile': Icons.psychology_outlined,
    'building.columns': Icons.account_balance_outlined,
    'calendar': Icons.calendar_today_outlined,
    'calendar.badge.clock': Icons.event_repeat_outlined,
    'camera.fill': Icons.photo_camera,
    'chart.bar': Icons.bar_chart,
    'chart.bar.doc.horizontal': Icons.insert_chart_outlined,
    'chart.bar.fill': Icons.bar_chart,
    'checklist': Icons.checklist,
    'checkmark': Icons.check,
    'checkmark.bubble.fill': Icons.mark_chat_read,
    'checkmark.circle': Icons.check_circle_outline,
    'checkmark.circle.fill': Icons.check_circle,
    'checkmark.seal': Icons.verified_outlined,
    'checkmark.seal.fill': Icons.verified,
    'checkmark.shield': Icons.verified_user_outlined,
    'checkmark.shield.fill': Icons.verified_user,
    'chevron.down': Icons.keyboard_arrow_down,
    'circle.fill': Icons.circle,
    'chevron.left': Icons.chevron_left,
    'chevron.right': Icons.chevron_right,
    'chevron.up': Icons.keyboard_arrow_up,
    'clock': Icons.schedule,
    'clock.badge.questionmark': Icons.history_toggle_off,
    'creditcard': Icons.credit_card,
    'creditcard.fill': Icons.credit_card,
    'cross.case': Icons.medical_services_outlined,
    'cross.case.fill': Icons.medical_services,
    'crown': CupertinoIcons.star_circle,
    'crown.fill': CupertinoIcons.star_circle_fill,
    'doc': Icons.description_outlined,
    'doc.badge.plus': Icons.note_add_outlined,
    'doc.fill': Icons.description,
    'doc.on.doc': Icons.copy_outlined,
    'doc.questionmark': Icons.quiz_outlined,
    'doc.richtext.fill': Icons.article,
    'doc.text': Icons.article_outlined,
    'doc.text.fill': Icons.article,
    'doc.text.magnifyingglass': Icons.plagiarism_outlined,
    'door.right.to.left.open': Icons.logout,
    'ellipsis': Icons.more_horiz,
    'ellipsis.circle': Icons.more_horiz,
    'envelope': Icons.mail_outline,
    'exclamationmark.circle': Icons.error_outline,
    'exclamationmark.magnifyingglass': Icons.search_off,
    'exclamationmark.triangle': Icons.warning_amber_outlined,
    'exclamationmark.triangle.fill': Icons.warning,
    'externaldrive': Icons.storage_outlined,
    'externaldrive.badge.plus': Icons.add_to_drive,
    'externaldrive.fill': Icons.storage,
    'eye': Icons.visibility_outlined,
    'eye.slash': Icons.visibility_off_outlined,
    'figure.and.child.holdinghands': Icons.family_restroom,
    'flask': Icons.science_outlined,
    'folder': Icons.folder_outlined,
    'folder.badge.gearshape': Icons.rule_folder_outlined,
    'folder.badge.plus': Icons.create_new_folder_outlined,
    'folder.badge.questionmark': Icons.folder_off_outlined,
    'folder.fill': Icons.folder,
    'function': Icons.functions,
    'heart.text.square': Icons.favorite_outline,
    'lungs': Icons.air,
    'pills': Icons.medication_outlined,
    'star.fill': Icons.star,
    'gearshape': Icons.settings_outlined,
    'graduationcap': Icons.school_outlined,
    'graduationcap.fill': Icons.school,
    'hand.raised': Icons.back_hand_outlined,
    'headphones': Icons.headphones_outlined,
    'highlighter': Icons.border_color_outlined,
    'hourglass': Icons.hourglass_empty,
    'icloud': Icons.cloud_outlined,
    'icloud.and.arrow.up': Icons.cloud_upload_outlined,
    'info.circle': Icons.info_outline,
    'info.circle.fill': Icons.info,
    'internaldrive': Icons.sd_storage_outlined,
    'internaldrive.fill': Icons.sd_storage,
    'iphone': Icons.phone_iphone,
    'key': Icons.key_outlined,
    'key.fill': Icons.key,
    'key.horizontal.fill': Icons.vpn_key,
    'leaf': Icons.eco_outlined,
    'line.3.horizontal.decrease.circle': Icons.filter_list,
    'link': Icons.link,
    'list.bullet': Icons.format_list_bulleted,
    'list.bullet.clipboard': Icons.assignment_outlined,
    'list.bullet.rectangle': Icons.list_alt,
    'list.number': Icons.format_list_numbered,
    'lock': Icons.lock_outline,
    'lock.fill': Icons.lock,
    'lock.rotation': Icons.screen_lock_rotation,
    'lock.shield': Icons.shield_outlined,
    'magnifyingglass': Icons.search,
    'mic': Icons.mic_none,
    'minus.circle.fill': Icons.remove_circle,
    'moon.stars': Icons.nights_stay_outlined,
    'mouth.fill': Icons.record_voice_over,
    'number': Icons.tag,
    'paintpalette': Icons.palette_outlined,
    'paperplane': Icons.send_outlined,
    'paperplane.fill': Icons.send,
    'pawprint.fill': Icons.pets,
    'pencil': Icons.edit_outlined,
    'person': Icons.person_outline,
    'person.badge.plus': Icons.person_add_alt,
    'person.badge.plus.fill': Icons.person_add,
    'person.crop.circle': Icons.account_circle_outlined,
    'person.fill': Icons.person,
    'person.text.rectangle': Icons.badge_outlined,
    'photo': Icons.image_outlined,
    'photo.badge.exclamationmark': Icons.broken_image_outlined,
    'photo.on.rectangle': Icons.photo_library_outlined,
    'play.fill': Icons.play_arrow,
    'play.rectangle': Icons.smart_display_outlined,
    'pause.fill': Icons.pause,
    'plus': Icons.add,
    'plus.circle.fill': Icons.add_circle,
    'plus.rectangle.on.folder': Icons.drive_folder_upload_outlined,
    'point.3.connected.trianglepath.dotted': Icons.hub_outlined,
    'questionmark.bubble': Icons.contact_support_outlined,
    'questionmark.circle': Icons.help_outline,
    'questionmark.circle.fill': Icons.help,
    'quote.bubble.fill': Icons.format_quote,
    'rectangle.on.rectangle': Icons.filter_none,
    'rectangle.stack': Icons.layers_outlined,
    'rectangle.stack.badge.exclamationmark': Icons.library_add_check_outlined,
    'rectangle.stack.badge.plus': Icons.library_add_outlined,
    'scope': Icons.center_focus_strong_outlined,
    'shield.checkered': Icons.security,
    'shield.lefthalf.filled': Icons.shield,
    'shippingbox.and.arrow.backward': Icons.unarchive_outlined,
    'slider.horizontal.3': Icons.tune,
    'sparkles': Icons.auto_awesome,
    'sparkles.rectangle.stack': Icons.auto_awesome_motion,
    'speedometer': Icons.speed,
    'square.and.arrow.up': Icons.ios_share,
    'square.grid.2x2': Icons.grid_view,
    'square.stack.3d.up': Icons.layers,
    'star': Icons.star_outline,
    'stethoscope': Icons.monitor_heart_outlined,
    'storefront': Icons.storefront_outlined,
    'tablecells': Icons.table_chart_outlined,
    'tablecells.fill': Icons.table_chart,
    'tag': Icons.sell_outlined,
    'target': Icons.track_changes,
    'testtube.2': Icons.biotech_outlined,
    'text.alignleft': Icons.format_align_left,
    'text.bubble': Icons.chat_outlined,
    'text.bubble.fill': Icons.chat,
    'timer': Icons.timer_outlined,
    'toll': Icons.toll,
    'trash': Icons.delete_outline,
    'tray.full': Icons.inbox,
    'wand.and.stars': Icons.auto_fix_high,
    'waveform': Icons.graphic_eq,
    'waveform.badge.exclamationmark': Icons.multitrack_audio,
    'waveform.path.ecg': Icons.monitor_heart,
    'wifi.slash': Icons.wifi_off,
    'xmark': Icons.close,
    'xmark.circle': Icons.cancel_outlined,
    'xmark.circle.fill': Icons.cancel,
  };

  static IconData named(String sfSymbol) =>
      _map[sfSymbol] ?? Icons.circle_outlined;
}

/// Drop-in replacement for `Image(systemName:)` with the SB scaled-font sizing.
class SBIcon extends StatelessWidget {
  const SBIcon(this.symbol, {super.key, this.size = 17, this.color});

  final String symbol;
  final double size;
  final Color? color;

  @override
  Widget build(BuildContext context) {
    return Icon(SBIcons.named(symbol),
        size: size * 1.18, color: color ?? IconTheme.of(context).color);
  }
}
